service: instance-scheduler
configValidationMode: off
provider:
  name: scaleway
  runtime: python311 # Available python runtimes are listed in documentation

  scwToken: ${env:SCW_SECRET_KEY} # Those are my own credentials for uploading the function 
  scwProject: ${env:SCW_DEFAULT_PROJECT_ID}
  scwRegion: ${env:SCW_REGION}
  secret: # Those are the cretentials given to the function
    SCW_ACCESS_KEY: ${env:SCW_ACCESS_KEY_FUNCTION}
    SCW_SECRET_KEY: ${env:SCW_SECRET_KEY_FUNCTION}
    SCW_DEFAULT_PROJECT_ID: ${env:SCW_DEFAULT_PROJECT_ID_FUNCTION}
    SCW_DEFAULT_REGION: ${env:SCW_DEFAULT_REGION_FUNCTION}
    SCW_DEFAULT_ZONE: ${env:SCW_DEFAULT_ZONE_FUNCTION}

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements
package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!.env'

functions:
  stopschedule:
    handler: handler.stopSchedule
    description: "stopSchedule"
    events:
      - schedule:
          rate: '00 19 * * 1-5'
    memoryLimit: 128
    maxScale: 1
#    privacy: "private"
  startschedule:
    handler: handler.startSchedule
    description: "startSchedule"
    events:
      - schedule:
          rate: '00 9 * * 1-5'
    memoryLimit: 128
    maxScale: 1
#    privacy: "private"


useDotenv: true
custom:
  pythonRequirements:
    pythonBin: /opt/homebrew/bin/python3.11